# ===============================
# Profil actif par défaut
# ===============================
spring:
  profiles:
    active: local

---
# ===============================
# Configuration LOCAL
# ===============================
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/monprojet?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: emprexemprex
    driver-class-name: com.mysql.cj.jdbc.Driver

---
# ===============================
# Configuration PROD (ex: EC2)
# ===============================
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/AI?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: "Emprex@2024!"
    driver-class-name: com.mysql.cj.jdbc.Driver

---
# ===============================
# Configuration COMMUNE (valable pour tous les profils)
# ===============================
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080


