#spring.datasource.url=jdbc:mysql://adresse_de_prod:3306/API?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=emprexemprex
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect





# ================================
# Base H2 locale (aucune install requise)
# ================================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# ================================
# JWT Key
# ================================
jwt.secret=mySuperSuperSecretKeyThatIsLongEnough12345
jwt.expiration=3600000

# ================================
# Serveur local
# ================================
server.port=